# Generated by Django 3.0.5 on 2022-01-03 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='描述')),
                ('types', models.SmallIntegerField(default=10, verbose_name='展现的位置')),
                ('img', models.ImageField(max_length=255, upload_to='%Y%m/slider', verbose_name='图片地址')),
                ('reorder', models.SmallIntegerField(default=0, help_text='数字越大越靠前', verbose_name='排序字段')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='生效开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='生效结束的时间')),
                ('target_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='跳转的地址')),
                ('is_valid', models.BooleanField(default=True, verbose_name='删除字段')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'db_table': 'system_slider',
                'ordering': ['-reorder'],
            },
        ),
        migrations.CreateModel(
            name='ImageRelated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_valid', models.BooleanField(default=True, verbose_name='删除字段')),
                ('img', models.ImageField(max_length=256, upload_to='%Y%m/file/', verbose_name='图片')),
                ('summary', models.CharField(blank=True, max_length=32, null=True, verbose_name='图片说明')),
                ('object_id', models.IntegerField(verbose_name='关联的模型')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(null=True, on_delete=models.SET(None), related_name='upload_images', to='accounts.User', verbose_name='上传的用户')),
            ],
            options={
                'db_table': 'system_image_related',
            },
        ),
    ]
