name: Unit tests (third-party PR)

on: [pull_request]

jobs:
  minimal_test_run:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    if: github.event.pull_request.base.repo.id != github.event.pull_request.head.repo.id

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: NPM install
      run: npm ci

    # - name: Lint TypeScript sources
    #   run: npm run lint

    - name: Bootstrap packages
      run: npm run bootstrap

    - name: Build packages
      run: npm run build

    - name: Unit tests
      run: npm run test:ci