"""empty message

Revision ID: cd6d84ec8c01
Revises: 
Create Date: 2022-02-27 14:03:30.210734

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd6d84ec8c01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='user')
    op.drop_table('user')
    op.drop_table('comment')
    op.drop_table('source')
    op.drop_table('cature')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cature',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('cature_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('cature_hash', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_table('source',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('source_msg', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('create_time', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updata_time', mysql.TIMESTAMP(), nullable=True),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_table('comment',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('Comment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('create_time', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updata_time', mysql.TIMESTAMP(), nullable=True),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_index('email', 'user', ['email'], unique=False)
    # ### end Alembic commands ###
