name: Fidelity tests

on: pull_request

jobs:
  compare_renders:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: NPM install
      run: npm ci

    # - name: Lint TypeScript sources
    #   run: npm run lint

    - name: Bootstrap packages
      run: npm run bootstrap

    - name: Build packages
      run: |
       ./node_modules/.bin/lerna run --scope @google/model-viewer build --stream
       ./node_modules/.bin/lerna run --scope @google/model-viewer-render-fidelity-tools build --stream

    - name: Fidelity tests
      uses: GabrielBB/xvfb-action@v1.0
      with:
        run: ./node_modules/.bin/lerna run --scope @google/model-viewer-render-fidelity-tools test --stream
