# Generated by Django 3.0.5 on 2022-01-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220103_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=32, null=True, unique=True, verbose_name='昵称'),
        ),
    ]
