name: CI
on:
  - push
  - pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  tests:
    strategy:
      matrix:
        node:
          - 14.x

    runs-on: ubuntu-20.04
    name: Node.js ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Npm update
        run: npm update
      - name: Npm install
        run: npm install
      - name: Tests
        run: npm run format-check